language: java

script:
- mvn clean package
after_script:
- echo "Script finished"
after_success:
- echo "Build was successful. $TRAVIS_TEST_RESULT"
after_failure:
- echo "Build was failed"

jdk:
  - oraclejdk8
  
branches:
  only:
    - develop
