language: java
dist: trusty

before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "
if [ ${TRAVIS_PULL_REQUEST} = 'false' ];
then 
    mvn clean deploy -U --batch-mode --settings target/travis/settings.xml; 
else 
    mvn clean verify -U --batch-mode --settings target/travis/settings.xml;
fi"

jdk:
  - oraclejdk8
  
branches:
  only:
    - develop

env:
  global:
    - secure: "U0qFS6VB7DjQhnd3Ac2ZoojGIkN2vCpGXLwmQMDIInJLKdtKniPsqyZKVC2OAsbM0OiSoP2Gq98FrJXGG6d2Qh/wt/ITLp3FU/fZh66k2xWZbdkTJpV1/Kvu3nJt1chcrCiFWX4c21+k0A177qyr4URjBN3afLnOenRnPb5CbsA5+OlEI+kErL1yEHEVgKmt6Ma3rY9aO7S9tpAQafh7Xtre4DVGc/xElaAs8PSVVi/EXn3IQK5XYh2IQ2QIvEn8NA7ULA/OHuaSZtea+zGuv9F3MK2PSjJu5UcSa9pycXPX57AVmjDAKl7Ebqg38w+/L6K0TmGQBFBFuw11qIzsQFuBR2nKMosz3BOxgm3thZYDIJGdTmIvyihHTZNiExvBUj+lnKurO0c0jOtBDpxaRIGDSfxJ57u4yLjJIkYGKkoGH0Ti7wR4OfBdne2Cn2iZqL5D5aElt8P4yHKTthBik72DQpv7T7L1GIy2316PDbJhsFi77lml7xpfEy7f8MykPF3nL5/OOAeWGjc1MIzLBAZWV/KBVdVIH6HARLG1oVcSZdTmnbZrjQt55EvJmdvj9HxQ3Q/uSUeyuuWty46iA96fmCrkMBSIJSEF+8+Wb54IjjnHSlRWoI1XZTcYXTDYq5mh1KRd4unWYO7GL4H2ozSkQ04YXiEql0abLlnyrCo="
    - secure: "NzSoXnvqOIa45w+Cetal4VXNp6e+dZfD3zW1QSy1XSn9sbQYkV2iUn+u4BRDgKcUsDDh53dJs7CgH8VqRm9ARJliMEdCeUcOHN0OY/CTW8Nmm3wVnwt6WBxUsw70QiowumWdGePmG0ycfmd0fbheesaJ/SsZ3JtBvBUrsQM8vs4Xo+bGrZ17ac6/tpqeqICs9E5VT76/g4kKxSjLP+EWk9RfQwCWcRqzHHsycmMtpzoyj8OtgWj++FEkA8NRqh+gHIdcX98MffuHUkpSuF/udRb6ZJt67BZMyVe10LOT1Q+tY4ZG6JPxhUTadjxWvN/gfjHaD3U8F4FyP3W0xQomIqbYln1B63lzLD+rC2F5IMcgCry6Kdr/4VfSKJJD7Bobloy8eYR9yuCvea2jUfcjrZ8car8fcQIuLrpIXcfdQcZMRq4XlQM1VI3x/j+9VMRx0YUhMaH6E6bgXRAheJ+bzfPBTjvbY3e5cSTRB5QQ0ETpwasaWddBg/4VKfkoKy29hNQnMNKMroHJglWxVtVZ95p+Jp3k8GcJFuTOJ+cmAmBLOaJCXHDvda4F9P21JiI6wLdvjJEc1WfllbZDlTYopQe4xST0HNhoRGLPze629+D7Y+218rfSd/BLcNH6O0QDZRbS2QTnT9T7U7pVeUFwprnFHip8BfIMkZFPwBTPIc8="
